# service: nodejs-mongodb-api

# provider:
#   name: aws
#   runtime: nodejs18.x
#   region: us-east-1
#   environment:
#     MONGODB_URI: "mongodb+srv://contactfixitupinfo:Bk6v2ZxzSyUpcGjR@cluster0.rlluj.mongodb.net/"
#     EMAIL_USER: contactfixitupinfo@gmail.com
#     EMAIL_PASS: yocbncukqjjsohvu

# functions:
#   api:
#     handler: lambda.handler
#     events:
#       - http:
#           path: /
#           method: ANY
#       - http:
#           path: /{proxy+}
#           method: ANY




